apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: shop
  labels:
    app: db
    tier: data
spec:
  replicas: 1
  strategy:
    type: Recreate          # a single RWO volume can't be shared during a rolling update
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        tier: data
    spec:
      containers:
        - name: postgres
          image: cr.lab.local/postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-credentials      # POSTGRES_USER / _PASSWORD / _DB
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "shop"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
