FROM docker.io/golang:1.22-alpine AS builder
WORKDIR /app
COPY main.go .
RUN go mod init api && go build -o api .

FROM scratch
COPY --from=builder /app/api /api
COPY data.json /data.json
ENTRYPOINT ["/api"]